# https://tasdikrahman.me/2017/04/06/Testing-your-ansible-roles-using-travis-CI/
# This was lifted from the amazing writeup above until I get a better grasp on
# what I'm doing.
---
notifications:
  email:
    on_success: never
    on_failure: change

sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest

install:
  - pip install ansible

script:
  # Check the role/playbook's syntax.
  - ansible-playbook test-venv.yml --syntax-check
  - ansible-playbook test-global.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  # - ansible-playbook test-env.yml -vvvv
  # - ansible-playbook test-global.yml -vvvv
