---
- name: "Ensure the temp location {{ tmp_dir }} exists"
  file:
    path: "{{ tmp_dir }}"
    state: directory
  notify: "Clean tmpdir"

- name: "Download the library"
  get_url:
    url: "{{ libgit2_tar_release }}"
    dest: "{{ tmp_dir }}/archive.tar.gz"

- name: "Extract the library"
  unarchive:
    src: "{{ tmp_dir }}/archive.tar.gz"
    dest: "{{ tmp_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: "Set the libgit2 install prefix to {{ build_location }}"
  environment:
    LIBGIT2: "{{ build_location }}"
  shell: 'cmake . -DCMAKE_INSTALL_PREFIX=$LIBGIT2'
  args:
    chdir: "{{ tmp_dir }}"

- name: "Build the library"
  shell: make
  args:
    chdir: "{{ tmp_dir }}"

- name: "Install the library"
  shell: make install
  args:
    chdir: "{{ tmp_dir }}"
  become: is_global_install
