---
- name: "Create a temp location for the files"
  tempfile:
    state: directory
    suffix: build
  register: tmpdir
  notify: "Clean tmpdir"

- name: "Download and extract the library"
  unarchive:
    src: "{{ libgit2_tar_release }}"
    dest: "{{ tmpdir.path }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: "Set the libgit2 install prefix"
  environment:
    LIBGIT2: "{{ build_location }}"
  shell: 'cmake . -DCMAKE_INSTALL_PREFIX=$LIBGIT2'
  args:
    chdir: "{{ tmpdir.path }}"

- name: "Build the library"
  shell: make
  args:
    chdir: "{{ tmpdir.path }}"

- name: "Install the library"
  shell: make install
  args:
    chdir: "{{ tmpdir.path }}"
  become: is_global_install
