---
- name: "Set the reused variables"
  set_fact:
    python_binary: python
    build_location: "{{ global_build_location }}"
    is_global_install: yes

- import_tasks: check_existing_libgit2.yml

- include_tasks: global_install.yml
  when: force_rebuild or has_libgit2 | changed


- name: "Install pygit2"
  pip:
    name: pygit2
    state: latest
  notify: "Test pygit2"
  become: yes

- name: "Configure the dynamic linker"
  shell: "ldconfig"
  become: yes
