---
- name: "Ensure {{ venv_build_location }} exists"
  file:
    dest: "{{ venv_build_location }}"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    state: directory

- name: "Ensure {{ venv_build_location }} is a virtualenv"
  shell: "virtualenv ."
  args:
    chdir: "{{ venv_build_location }}"
    creates: "{{ venv_build_location }}/bin/activate"

- import_tasks: build_libgit2.yml
