---
- name: "Set the reused variables"
  set_fact:
    python_binary: "{{ venv_build_location }}/bin/python"
    build_location: "{{ venv_build_location }}"
    is_global_install: no

- block:
  - debug:
      var: venv_build_location
  - debug:
      var: python_binary
  - debug:
      var: build_location
  - debug:
      var: is_global_install

- import_tasks: check_existing_libgit2.yml

- include_tasks: virtualenv_install.yml
  when: force_rebuild or has_libgit2 | changed

- name: "Install pygit2 to {{ venv_build_location }}"
  environment:
    LIBGIT2: "{{ venv_build_location }}"
    LDFLAGS: "{{ '-WL,-rpath=\"$LIBGIT2/lib\",--enable-new-dtags $LDFLAGS' if is_glibc else omit }}"
    LD_LIBRARY_PATH: "{{ venv_build_location }}/lib"
  block:
  - debug:
      var: LIBGIT2
  - debug:
      var: LDFLAGS
  - debug:
      var: LD_LIBRARY_PATH
  - debug:
      var: is_glibc
  - shell: ". {{ venv_build_location }}/bin/activate && {{ venv_build_location }}/bin/pip install --no-cache pygit2"
    notify: "Test pygit2"
